### ISSUE TITLE
How to use graphql-yoga server in this project

### ISSUE THREAD

**Issue by fogelfish** [artflutter/graphql_flutter_bloc#2]
Since this project demonstrates bloc subscriptions, could you include in the readme how to set up and use graphql-yoga?

It's new to me how graphql-faker makes it so easy to mock up a local graphql schema but I believe that its server does not support subscriptions, which is why you included the subscription_server folder in the project, but is there a way to create a fake schema for the graphql-yoga server or even use the same fake.schema?

**Comment by vasilich6107** [comment]
Hi. Setting up subscription server tutorial is out of scope for this library.
I included `subscription_server` only for testing purposes while developing the library.
Please refer to `graphql-yoga` readme or issue tracker.
