### ISSUE TITLE
How to generate q.schema.graphql / models/graphql ?

### ISSUE THREAD

**Issue by tibfox** [artflutter/graphql_flutter_bloc#4]
I wanted to combine graphql_flutter with flutter_bloc and found out that this repo is the way the developers of graphql_flutter recommend to use. But I have no idea how to generate some files seen in the example... I think I am missing something and since the documentation is not existing except for an example and obviously not many people have use the repo I ask for your help here:

How is https://github.com/artflutter/graphql_flutter_bloc/blob/master/example/graphql/q/q.schema.graphql generated? It says "# This file was generated based on ".graphqlconfig". Do not edit manually."

Same for all the files in https://github.com/artflutter/graphql_flutter_bloc/tree/master/example/lib/models/graphql where it says "// GENERATED CODE - DO NOT MODIFY BY HAND"

And another question: Is this repo active? I have not found any information of other people using it so far and I am a bit scared to recode a lot of parts of my app without being future proof.

Thanks for your response!

**Comment by vasilich6107** [comment]
@tibfox you don’t have to generate the code to use this library

**Comment by vasilich6107** [comment]
You can also check this article
https://medium.com/@v.ditsyak/ultimate-toolchain-to-work-with-graphql-in-flutter-13aef79c6484

**Comment by tibfox** [comment]
Thanks for the article! It seems that I will need to write those files above (especailly those under modesl/graphql) all by myself because I use VSCode instead of android studio and JS Graphql is not an option for me. And if that's the case far as it seams that would just be too much effort at the moment for my project even though the end result would be very convenient. I knew that it would be much work but that's simply too much I guess and I should stick with the original code nesting my graphql logic inside of the widget tree. I just assumed it will be an easier transition :)
